### ISSUE TITLE
Store changes in Mongo or any DB

### ISSUE THREAD

**Issue by JinwookKim** [JinwookKim/cc-scraper#44]
Possibly have a history of all the changes that has been made in the data within the databases for tracking trends or be able to rollback info. Or just look at the history. 

similar to this: https://stackoverflow.com/questions/4185105/ways-to-implement-data-versioning-in-mongodb

**Comment by ctu95** [comment]
Will you set up a centralized data repository for history? I don't quite understand how it might work and stay persisted if this cc-scraper library will work as a NPM package?

**Comment by JinwookKim** [comment]
You're right. This issue should be on the backend repo LOL
